### ISSUE TITLE
Suggestion: add pagination info to collections

### ISSUE THREAD

**Issue by jenssegers** [teamleadercrm/api#8]
Suggestion; add pagination information as "meta-data" to collections. Since we can't do `select count(*)` from the proxy it is probably best if we simply add cursor information. Example from http://fractal.thephpleague.com/pagination/

```json
{
	"data": [
		...
	],
	"meta": {
		"cursor": {
			"previous": null,
			"current": 5,
			"next": 10,
			"count": 5
		}
	}
}
```

**Comment by Brammm** [comment]
@jenssegers I started working on this, but ran into some issues/questions:

- We're promoting POSTs over GETs and putting the pagination in the request, instead of the uri. So is there benefit to to still adding it to the uri here? The Fractal way would make more sense then instead of the JSONAPI way.
- Adding to that, Slim is pretty obnoxious in urlencoding the Uri query string, resulting in URLs that look like `http://localhost/?page%5Bnumber%5D=5&page%5Bsize%5D=20`, so should we keep the pagination parameters in a nested array?
